### ISSUE TITLE
Can I use it in a Java project? If yes, how?

### ISSUE THREAD

**Issue by ShahoodulHassan** [betterme-dev/RxBilling#8]

**Comment by dmytro-ostapovets** [comment]
@ShahoodulHassan No, it's an android library

**Comment by KChernenko** [comment]
@ShahoodulHassan and yes, if you have an Android project written in Java.

**Comment by ShahoodulHassan** [comment]
@KChernenko spot on! Thats what I wanted to know.
But aint it written in Kotlin?

**Comment by KChernenko** [comment]
@ShahoodulHassan Kotlin has full interop with Java, so you can mix and match source code written in both languages.

**Comment by ShahoodulHassan** [comment]
Ok but can i get the documentation for this library translated in Java?
Whatever instructions in Kotlin that have been given therein are all gibberish for me.

**Comment by vladp** [comment]
@ShahoodulHassan   kotlin is like a 'macro' language for Java.
a translation is very easy, in most instances, if you use intuition it works.
For example,     
`rxBilling = RxBillingImpl(BillingClientFactory(applicationContext))`

translates to

```

        BillingClientFactory cf=
        new BillingClientFactory(this.getActivity().getApplicationContext(), new RepeatConnectionTransformer<>());
        rxBilling= new RxBillingImpl(cf);

```

I think authors of the library could make some specific comments as it relates to Java.
Because Kotlin allows default function/constructor arguments, but Java does not
so 
`BillingClientFactory(applicationContext)`

does not directly translate to java's    `new BillingClientFactory (appContext)`
because the constructor actually requires a second argument (which is declared in library's Kotlin code)
`RepeatConnectionTransformer
`

**Comment by KChernenko** [comment]
I
